
import Footer from "@/components/shared/Footer";
import "./globals.css";
import Header from "@/components/shared/Header";



export const metadata = {
  title: "News Portal Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <Header></Header>
        
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
